# Run Sketchybar together with AeroSpace
# sketchbar has a built-in detection of already running process,
# so it won't be run twice on AeroSpace restart
after-startup-command = [
	'exec-and-forget sketchybar',
	'exec-and-forget /opt/homebrew/bin/borders active_color=0xffff6600 inactive_color=0xff494d64 width=3.0'
]


# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

[gaps]
inner.horizontal = 15
inner.vertical = 15
outer.bottom = 15
outer.top = [
  { monitor."built-in" = 20 },
  { monitor."main" = 50 },
  50
]
outer.left = 15
outer.right = 15

[mode.main.binding]
	cmd-ctrl-alt-shift-t = 'workspace terminal'
	cmd-ctrl-alt-shift-w = 'workspace web'
	cmd-ctrl-alt-shift-o = 'workspace obsidian'
	cmd-ctrl-alt-shift-c = 'workspace communication'
	cmd-ctrl-alt-shift-m = 'workspace music'
	cmd-ctrl-alt-shift-b = 'workspace bot'
 
	alt-shift-t = 'move-node-to-workspace terminal'
	alt-shift-w = 'move-node-to-workspace web'
	alt-shift-o = 'move-node-to-workspace obsidian'
	alt-shift-c = 'move-node-to-workspace communication'
	alt-shift-m = 'move-node-to-workspace music'
	alt-shift-b = 'move-node-to-workspace bot'

	# See: https://nikitabobko.github.io/AeroSpace/commands#layout
	alt-slash = 'layout tiles horizontal vertical'
	alt-comma = 'layout accordion horizontal vertical'

	# See: https://nikitabobko.github.io/AeroSpace/commands#focus
	cmd-ctrl-alt-shift-h = 'focus left'
	cmd-ctrl-alt-shift-j = 'focus down'
	cmd-ctrl-alt-shift-k = 'focus up'
	cmd-ctrl-alt-shift-l = 'focus right'

	# See: https://nikitabobko.github.io/AeroSpace/commands#move
	alt-shift-h = 'move left'
	alt-shift-j = 'move down'
	alt-shift-k = 'move up'
	alt-shift-l = 'move right'

	# See: https://nikitabobko.github.io/AeroSpace/commands#resize
	alt-minus = 'resize smart -50'
	alt-equal = 'resize smart +50'

	# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
	cmd-ctrl-alt-shift-tab = 'workspace-back-and-forth'
	# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
	alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

	# See: https://nikitabobko.github.io/AeroSpace/commands#mode
	alt-shift-semicolon = 'mode service'
