# Run Sketchybar together with AeroSpace
# sketchbar has a built-in detection of already running process,
# so it won't be run twice on AeroSpace restart
after-startup-command = [
	'exec-and-forget sketchybar',
	'exec-and-forget /opt/homebrew/bin/borders active_color=0xffff6600 inactive_color=0xff494d64 width=3.0'
]


# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

# Notify Sketchybar about window changes (opens/closes)
on-focus-changed = [
    'exec-and-forget sketchybar --trigger aerospace_windows_change',
    'exec-and-forget touch /tmp/aerospace_focus_test'
]

# Start AeroSpace at login
start-at-login = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
# accordion-padding = 30

[gaps]
  inner.vertical = 15
  inner.horizontal = 15
  outer.bottom = 15
  outer.top = [
    { monitor."main" = 50 },
    { monitor."built-in" = 20 },
    50
  ]
  outer.left = 15
  outer.right = 15

# Auto-move apps to workspaces
[[on-window-detected]]
  if.app-name-regex-substring = 'WezTerm'
  run = ['move-node-to-workspace terminal']

[[on-window-detected]]
  if.app-name-regex-substring = 'Arc'
  run = ['move-node-to-workspace web']

[[on-window-detected]]
  if.app-name-regex-substring = 'Obsidian'
  run = ['move-node-to-workspace obsidian']

[[on-window-detected]]
  if.app-name-regex-substring = 'Slack'
  run = ['move-node-to-workspace communication']

[[on-window-detected]]
  if.app-name-regex-substring = 'YouTube Music'
  run = ['move-node-to-workspace music']

[[on-window-detected]]
  if.app-name-regex-substring = 'Claude'
  run = ['move-node-to-workspace bot']

[mode.main.binding]
	shift-ctrl-alt-t = ['exec-and-forget open /Applications/WezTerm.app', 'workspace terminal']
	shift-ctrl-alt-w = ['exec-and-forget open /Applications/Arc.app', 'workspace web']
	shift-ctrl-alt-o = ['exec-and-forget open /Applications/Obsidian.app', 'workspace obsidian']
	shift-ctrl-alt-c = ['exec-and-forget open /Applications/Slack.app', 'workspace communication']
	shift-ctrl-alt-m = ['exec-and-forget open ~/Applications/Chrome\ Apps.localized/YouTube\ Music.app', 'workspace music']
  shift-ctrl-alt-b = ['exec-and-forget open /Applications/Claude.app', 'workspace bot']

	# shift-ctrl-alt-b = 'workspace bot'
 
	cmd-ctrl-alt-shift-t = 'move-node-to-workspace terminal'
	cmd-ctrl-alt-shift-w = 'move-node-to-workspace web'
	cmd-ctrl-alt-shift-o = 'move-node-to-workspace obsidian'
	cmd-ctrl-alt-shift-c = 'move-node-to-workspace communication'
	cmd-ctrl-alt-shift-m = 'move-node-to-workspace music'
	cmd-ctrl-alt-shift-b = 'move-node-to-workspace bot'

	# See: https://nikitabobko.github.io/AeroSpace/commands#layout
	shift-ctrl-alt-slash = 'layout tiles horizontal vertical'
	shift-ctrl-alt-comma = 'layout accordion horizontal vertical'

	# See: https://nikitabobko.github.io/AeroSpace/commands#focus
	ctrl-alt-shift-h = 'focus --boundaries all-monitors-outer-frame left'
	ctrl-alt-shift-j = 'focus --boundaries all-monitors-outer-frame down'
	ctrl-alt-shift-k = 'focus --boundaries all-monitors-outer-frame up'
	ctrl-alt-shift-l = 'focus --boundaries all-monitors-outer-frame right'

	# See: https://nikitabobko.github.io/AeroSpace/commands#move
	cmd-ctrl-alt-shift-h = 'move left'
	cmd-ctrl-alt-shift-j = 'move down'
	cmd-ctrl-alt-shift-k = 'move up'
	cmd-ctrl-alt-shift-l = 'move right'

	# See: https://nikitabobko.github.io/AeroSpace/commands#resize
	shift-ctrl-alt-minus = 'resize smart -50'
	shift-ctrl-alt-equal = 'resize smart +50'

	# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
	shift-ctrl-alt-tab = 'workspace-back-and-forth'
	# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
	cmd-ctrl-alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

	# See: https://nikitabobko.github.io/AeroSpace/commands#mode
	alt-shift-semicolon = 'mode service'
